spring.application.name=Customer_Crud

# === Database Configuration ===
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# === JPA Configuration ===
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# == secret key ===
jwt.secret=Y2wV9xYsuA+rY8dVoTh5IATGzW23ZkC8sKvP1lEPQmc=